blank_issues_enabled: false
contact_links:
  - name: LIGR Help Center
    url: https://help.ligr.live/en/
    about: Get help with account, login, billing, or general application and website problems.
